### ISSUE TITLE
dislike count issue

### ISSUE THREAD

**Issue by noobtoob4lyfe** [ibaiGorordo/Midasv2_1_small-TFLite-Inference#1]
since youtube removed dislikes there seems to be an issue when this part of the code is reached.  

line 54, in _fetch_basic
    self._dislikes = self._ydl_info['dislike_count']
KeyError: 'dislike_count'

**Comment by ibaiGorordo** [comment]
Yeah, I have stopped using pafy in the latest repositories I uploaded. The solution seems to be to use a git version instead of the pypi version:
https://github.com/mps-youtube/pafy/pull/305#issuecomment-986212672

Hopefully the official pafy library release is updated, but it will probably take time...

**Comment by ibaiGorordo** [comment]
Hi,

If you try the latest youtube-dl version, the issue seems to have been solved:
`pip install pafy youtube_dl --upgrade`
